language: php

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.4
  - 'nightly'

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0
    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0
    - php: 7.2
      env: COVERAGE=1 DEFAULT=0

  fast_finish: true

before_install:
  - |
      if [[ $TRAVIS_PHP_VERSION != 'nightly' ]]; then
        phpenv config-rm xdebug.ini
      fi

  - |
      if [[ $COVERAGE == 1 ]]; then
        pecl channel-update pecl.php.net
        pecl install pcov
      fi

install:
  - composer install --no-interaction --prefer-dist --ignore-platform-reqs
  - if [[ $PHPSTAN == 1 ]]; then composer phpstan-setup; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit --verbose; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs src/ tests/; fi
  - if [[ $PHPSTAN == 1 ]]; then composer phpstan; fi
  - if [[ $COVERAGE == 1 ]]; then vendor/bin/phpunit --verbose --coverage-clover=clover.xml; fi

after_success:
  - |
      if [[ $COVERAGE == 1 ]]; then
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        chmod +x php-coveralls.phar
        ./php-coveralls.phar
      fi

notifications:
  email: false
